#!/bin/bash
# Copyright © 2016 Fedor Mankov envieid0c (envieidoc@gmail.com)

INTERFACE=`networksetup -listallnetworkservices | grep USB`
CONF=/Library/Application\ Support/WLAN/com.realtek.utility.wifi/

function test_dns {
  if [ "nslookup -type=txt debug.opendns.com | grep 127.0.0.1 | awk '{print "127.0.0.1"}' | tail -n1" = '127.0.0.1' ]
then
  /usr/local/sbin/io_wnu_popup -title 'DNSCrypt not enabled' -message '' -timeout 3
else
  /usr/local/sbin/io_wnu_popup -title 'DNSCrypt enabled' -message '' -timeout 3
fi
}

  exec 6<&0
  exec < /Library/Application\ Support/WLAN/com.realtek.utility.wifi/MAC
  read a1
  StatusBarApp_POPUP="$(/usr/local/sbin/io_wnu_popup -title 'I/O Wireless Network Utility' -message 'Actions?' -actions 'Enable Wi-Fi',"Disable Wi-Fi","Fix Device","Enable TOR","Disable TOR","Enable DNSCrypt","Disable DNSCrypt","Enable OpenVPN","Disable OpenVPN","Enable Service","Disable Service","Show Utility","Hide Utility" -timeout 30 -sound default -appIcon /Library/Application\ Support/WLAN/StatusBarApp.app/Contents/Resources/ModelIcon.icns)"
      case $StatusBarApp_POPUP in
        "@TIMEOUT") `pkill -f ~/.io_wnuup` ;;
        "@CLOSED") echo "You clicked on the default alert' close button" ;;
        "@CONTENTCLICKED") echo "You clicked the alert's content !" ;;
        "@ACTIONCLICKED") echo "You clicked the alert default action button" ;;
        "Enable Wi-Fi") osascript -e 'quit app "StatusBarApp"' ; echo "1" > "$a1" ; echo "0" > "$a1" ; open -a /Library/Application\ Support/WLAN/StatusBarApp.app ;;
        "Disable Wi-Fi") osascript -e 'quit app "StatusBarApp"' ; echo "1" > "$a1" ; open -a /Library/Application\ Support/WLAN/StatusBarApp.app ;;
        "Fix Device") grep -rl "0" "$CONF"*rfoff.rtl > "$CONF"MAC ; cat "$CONF"MAC | cut -c 60-71 > "$CONF"DEVICE ;;
        "Enable TOR")  networksetup -setsocksfirewallproxy "$INTERFACE" 127.0.0.1 9050 off ; /usr/local/sbin/tor & sleep 3 ; open https://check.torproject.org ;;
        "Disable TOR") killall -9 tor ; networksetup -setsocksfirewallproxystate "$INTERFACE" off ;;
        "Enable DNSCrypt") sudo /usr/local/sbin/dnscrypt-proxy -a 127.0.0.1:53 -r 91.214.71.181:5353 --provider-name=2.dnscrypt-cert.ru.d0wn.biz --provider-key=0ECA:BC40:E0A1:335F:0221:4240:AB86:2919:D16A:2393:CCEB:4B40:9EB9:4F24:3077:ED99 & networksetup -setdnsservers "$INTERFACE" 127.0.0.1 && test_dns;;
        "Disable DNSCrypt") sudo killall -9 dnscrypt-proxy ; networksetup -setdnsservers "$INTERFACE" Empty && /usr/local/sbin/io_wnu_popup -title 'DNSCrypt disabled' -message '' -timeout 3 ;;
        "Enable Service") bash ~/.io_wnuup & ;;
        "Disable Service") pkill -f ~/.io_wnuup ;;
        "Enable OpenVPN") /usr/local/sbin/openvpn --config ~/config.ovpn & ;;
        "Disable OpenVPN") killall -9 openvpn ;;
        "Show Utility") osascript -e 'quit app "StatusBarApp"' ; echo "1" > "$a1" ; echo "0" > "$a1" ; open -a /Library/Application\ Support/WLAN/StatusBarApp.app ;;
        "Hide Utility") osascript -e 'quit app "StatusBarApp"' ; echo "1" > "$a1" ;;
        **) echo "? --> $StatusBarApp_POPUP" ;;
      esac
